services:
  nginx:
    ports: !override
      - "8080:80"
      - "8443:443"

  api:
    environment:
      COOKIE_SECURE: "false"
      SWAGGER_ENABLED: "false"
      SERVE_UPLOADS: "false"

  web:
    build:
      args:
        NEXT_PUBLIC_SITE_URL: ${LOCAL_NEXT_PUBLIC_SITE_URL:-http://${STUDIO_DOMAIN}:8080}
    environment:
      NEXT_PUBLIC_SITE_URL: ${LOCAL_NEXT_PUBLIC_SITE_URL:-http://${STUDIO_DOMAIN}:8080}

  admin:
    build:
      args:
        NEXT_PUBLIC_SITE_URL: ${LOCAL_NEXT_PUBLIC_SITE_URL:-http://${STUDIO_DOMAIN}:8080}
    environment:
      NEXT_PUBLIC_SITE_URL: ${LOCAL_NEXT_PUBLIC_SITE_URL:-http://${STUDIO_DOMAIN}:8080}
